setwd("C:/Radha/VIT/Winter 2021_22/R_Programs")
data_Set=read.csv("C:/Radha/VIT/Winter 2021_22/R_Programs/import d.csv")
names(data_set)
head(data_set)
plot(data_set)
LR_result=lm(y~x,data=data_set)
abline(LR_result,col="green")
summary(LR_result)
LR_result
x=data.frame(x=6:8)
predict(LR_result,x)
x=data.frame(x=c(6,7))
predict(LR_result,x)
